### ISSUE TITLE
Doubling up URL's

### ISSUE THREAD

**Issue by nickmoreton** [wagtail-packages/wagtail-devtools#5]
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/venv/lib/python3.8/site-packages/wagtail_devtools/management/commands/_base_admin_responses.py", line 61, in handle
    report["function"](*report["args"])
  File "/venv/lib/python3.8/site-packages/wagtail_devtools/management/commands/_base_admin_responses.py", line 203, in report_pages
    response = session.get(page["url"])
  File "/venv/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/venv/lib/python3.8/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/venv/lib/python3.8/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/venv/lib/python3.8/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/venv/lib/python3.8/site-packages/requests/models.py", line 436, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: http://localhost:8000http://localhost:8000/blogs/fostering/
```

**Comment by nickmoreton** [comment]
Fixed in https://github.com/wagtail-packages/wagtail-devtools/pull/8
